kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev-env 
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      component: dev-env
  template:
    metadata:
      labels:
        component: dev-env
    spec:
      containers:
        - name: dev-env
          image: {{ .Values.image }}
          securityContext: 
              privileged: true 
          volumeMounts: 
            - name: docker-graph-storage 
              mountPath: /var/lib/docker 
            - name: dat-volume 
              mountPath: /dat
            - name: ssh-key-volume
              mountPath: /root/ssh 
      imagePullSecrets:
        - name: acr-creds
      volumes: 
        - name: docker-graph-storage 
          emptyDir: {}
        - name: dat-volume
          emptyDir: {} 
        - name: ssh-key-volume
          secret:
            secretName: ssh-key
